### ISSUE TITLE
Version command error

### ISSUE THREAD

**Issue by jonesaustindev** [teamairship/airfoil#50] opened 2021-09-07 21:23 UTC
## Expected results

Running the version command should increment my project correctly (ex. patch `0.0.1` -> `0.0.2`)

## Observed results

Currently an error is being thrown because the version command is relying on the library `react-native-version` and that library seems to not be actively maintained. The error occurs because it cannot find the tvOS directory for the iOS project. The newest versions of React Native no longer contain the tvOS directory.

### Logs

```
Error: Command failed: npx react-native-version --skip-tag --never-amend

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npx react-native-version --skip-tag --never-amend',
  stdout: '[RNV] Versioning Android...\n' +
    '[RNV] Android updated\n' +
    '[RNV] Versioning iOS...\n' +
    "[RNV] Error: ENOENT: no such file or directory, open '/Users/austin/airship/prayer-app/ios/prayFirst-tvOS/Info.plist'\n" +
    'Usage: react-native-version [options] [projectPath]\n' +
    '\n' +
    'Version your React Native or Expo app in a `npm version` fashion.\n' +
    '\n' +
    'Options:\n' +
    '  -V, --version                output the version number\n' +
    '  -a, --amend                  Amend the previous commit. This is done\n' +
    '                               automatically when react-native-version is run\n' +
    '                               from the "version" or "postversion" npm script.\n' +
    '                               Use "--never-amend" if you never want to amend.\n' +
    '                               Also, if the previous commit is a valid\n' +
    '                               npm-version commit, react-native-version will\n' +
    '                               update the Git tag pointing to this commit.\n' +
    `  --skip-tag                   For use with "--amend", if you don't want to\n` +
    '                               update Git tags. Use this option if you have\n' +
    '                               git-tag-version set to false in your npm config\n' +
    '                               or you use "--no-git-tag-version" during\n' +
    '                               npm-version.\n' +
    '  -A, --never-amend            Never amend the previous commit.\n' +
    '  -b, --increment-build        Only increment build number.\n' +
    '  -B, --never-increment-build  Never increment build number.\n' +
    '  -d, --android [path]         Path to your "android/app/build.gradle" file.\n' +
    '                               (default: "android/app/build.gradle")\n' +
    '  -i, --ios [path]             Path to your "ios/" folder. (default: "ios")\n' +
    '  -L, --legacy                 Version iOS using agvtool (macOS only). Requires\n' +
    '                               Xcode Command Line Tools.\n' +
    '  -q, --quiet                  Be quiet, only report errors.\n' +
    '  -r, --reset-build            Reset build number back to "1" (iOS only).\n' +
    `                               Unlike Android's "versionCode", iOS doesn't\n` +
    '                               require you to bump the "CFBundleVersion", as\n' +
    '                               long as "CFBundleShortVersionString" changes. To\n' +
    '                               make it consistent across platforms,\n' +
    '                               react-native-version bumps both by default. You\n' +
    '                               can use this option if you prefer to keep the\n' +
    '                               build number value at "1" after every version\n' +
    '                               change. If you then need to push another build\n' +
    '                               under the same version, you can use "-bt ios" to\n' +
    '                               increment.\n' +
    '  -s, --set-build <number>     Set a build number. WARNING: Watch out when\n' +
    '                               setting high values. This option follows\n' +
    "                               Android's app versioning specifics - the value\n" +
    '                               has to be an integer and cannot be greater than\n' +
    '                               2100000000. You cannot decrement this value\n' +
    '                               after publishing to Google Play! More info at:\n' +
    '                               https://developer.android.com/studio/publish/versioning.html#appversioning\n' +
    '  --generate-build             Generate build number from the package version\n' +
    '                               number. (e.g. build number for version 1.22.3\n' +
    '                               will be 1022003)\n' +
    '  -t, --target <platforms>     Only version specified platforms, e.g. "--target\n' +
    '                               android,ios".\n' +
    '  -h, --help                   output usage information\n' +
    '[RNV] Done, with errors.\n',
  stderr: ''
}
```

## Steps to reproduce

`airfoil version patch`

**Comment by townofdon** [comment] 2021-09-14 19:03
@jonesaustindev I could not reproduce this error.

I tried creating a new airfoil project from both the `blimp` and `jet` templates. In each instance, navigating into the project root and running `airfoil version patch` worked for me.

I think the issue may be related to a target being removed from the folder structure, but not removed from an XCode project (the missing target may still be linked inside XCode).

The source code for `react-native-version` just iterates through all of the XCode projects and targets and bumps the versions of each. See: https://github.com/stovmascript/react-native-version/blob/master/index.js#L397

Closing this for now - if this is still an issue please feel free to re-open.

**Closed by townofdon** 2021-09-14 19:03 UTC
Labels: bug
